### ISSUE TITLE
Request: Sort housing items to match ingame housing item list

### ISSUE THREAD

**Issue by Tsusai** [jawslouis/MakePlacePlugin#1]
Just throwing this out there, not sure if it's possible.
Is there a way to have the items in the plugin interface, sort to match the list of housing items in the XIV interface?

**Comment by jawslouis** [comment]
I'm not sure either, will have to look into it. 
Will be some time before I can get to it though, since there's still a lot on my to-do

**Comment by Tsusai** [comment]
Closing this
With the modifications you've made in your recent release, my request is kinda moot.
Nicely done with the Unreal Engine interface.
