### ISSUE TITLE
Can't install plugin after game got update

### ISSUE THREAD

**Issue by Moogle51151** [jawslouis/MakePlacePlugin#10]
Hi.
Because the CN server cannot use XIVlauncher,so I have to run MakePlace by using the Dalamud plugin.Before the game is updated (CN-6.1ver.),I can use the normal version of MakePlace plugin.After the game was updated, the plugin crashed when I load the MakePlace file (.json).Dalamud reminds me that the MakePlace plugin is damaged and needs to be reinstalled.When I reinstall the plug-in, Dalamud prompts: MakePlace plug-in cannot be installed. Please restart the game and try again. If the problem still occurs, please contact the plug-in developer.After restarting the game, it still can't be installed. I even reinstalled the game on another disk of my computer, and the plug-in still can't be installed.
Help! How should I solve this problem?

**Comment by jawslouis** [comment]
Hey sorry the plugin is only meant for international server. There was a time when the international and CN server were using the same API, so it could load on CN servers. But the API for the international server has changed, so it can't be used now.
