### ISSUE TITLE
Suggestion: Filter items not included in saved layout

### ISSUE THREAD

**Issue by Sinule** [jawslouis/MakePlacePlugin#11]
Firstly, thank you so much for this plugin, I use it an unhealthy amount (venue decorator), and a lot of what I do simply wouldn't be feasible without it! 

One of my regular tasks is to change the layout of houses to previously saved ones (for themed events usually), and then change them back (or to other saved layouts). The layouts often re-use 20-80% of items which are already placed in the house, so it would be so much more efficient if the plugin could present me with a list of items which are currently placed in the house, but are not part of a layout file I have loaded. This would enable me to fairly easily store those items (using the in game furnishings list) and then add in the items which are missing from the new layout.

I don't know how feasible this is, or if perhaps there's a way to do this already that I've overlooked, but thank you for taking the time to read this.

**Comment by jawslouis** [comment]
Hey this feature already exists. If you scroll to the bottom of the plugin window, you'll see the "Unused Furniture" section.
