### ISSUE TITLE
Newest Version For Desktop Application Lag

### ISSUE THREAD

**Issue by Dapperling** [jawslouis/MakePlacePlugin#16]
There seems to be an issue with the newest desktop update having continuous lag for some users. Seems common with people using AMD cards. 
Previous version of the desktop app worked and ran smooth - as of downloading the newest there is major screen tearing and movement lag to the point of it being unusable.

**Comment by jawslouis** [comment]
Running the app in Dx11 mode might help
https://wiki.makeplace.app/ffxiv/app/troubleshooting#app-crashes

Closing this issue as this github is meant for the plugin only. If you still have trouble with the app, you can get help on the discord server.
