### ISSUE TITLE
Save Dialog

### ISSUE THREAD

**Issue by Blasphemous666** [jawslouis/MakePlacePlugin#19]
I am clueless about github but this is the only place I could find to talk about this.  The new dialogue to open/save a MP file adds time to getting things placed.  Sometimes small micro-adjustments need to be made so I'll use the program to change it but then just rather clicking "load" on the already shown path, it opens a window and I have to find the file, click it, then choose open.  If I'm doing twenty different small adjustments this will get old fast.

At the very least can we double-click the file to open it?  Or have the option to skip the dialog?  Anyway, thanks for the great work otherwise. Your mod/program have made housing awesome.

**Comment by jawslouis** [comment]
For your case, it sounds like you're doing many adjustments in-game. I would recommend using the BDTH plugin instead to do the adjustments, and you can save the final design using the MakePlace plugin.
