### ISSUE TITLE
Request: Highlight duplicates

### ISSUE THREAD

**Issue by gucciBane** [jawslouis/MakePlacePlugin#20]
Hiya,

Is it possible to have the plugin highlight, or somehow note if 2+ furnishings are the same item and in the exact same location? For instance, I must've placed 4 of the same thing getting ready to run Makeplace without thinking I only needed 1, then ended up realizing hours later that I had 4 identical pillars standing on top of each other.

Great plugin, thank you so much!

**Comment by jawslouis** [comment]
It sounds like you had 4 identical pillars overlapping, and only 1 of them was used in the design file. In this case, the other 3 pillars would appear in the "Unused Furniture" section of the plugin. So that would be the best way to check your design in-game.
