### ISSUE TITLE
A couple issues

### ISSUE THREAD

**Issue by caztopia** [jawslouis/MakePlacePlugin#21]
Hi! I've face some some issues and I'm trying to figure out why things are not working for me but here's a list below

-Blank Partition does not place correctly ingame so I tried export the layout ingame to the app to edit them but in the app it shows that the partitions are placed correctly not out of the place. Here's the picture comparison [Here](https://imgur.com/a/g5qDh5I)

-Since after the update, I export the ingame layout into the app but nothing is showing up in the app at all

**Comment by jawslouis** [comment]
Hey the wallpapers on blank partitions were not detected by the plugin until the latest update.
If you're still having issues after updating to the latest plugin version, the best place to get help would be on the Discord.
