### ISSUE TITLE
Already placing items

### ISSUE THREAD

**Issue by AmmarIrsan** [jawslouis/MakePlacePlugin#22]
![Screenshot 2023-07-15 025834](https://github.com/jawslouis/MakePlacePlugin/assets/54728257/23b05198-ee35-4860-ba8d-708461f3928d)
When I use Apply Interior Layout button, a message pops up saying "Already placing items"

Last thing that happened is the game crashed while using the plugin, tried restarting the game, laptop, and the plugin itself.

**Comment by jawslouis** [comment]
Usually restarting the plugin would fix the issue. If you're still running into problems, the fastest way to get help is on the Discord server, in the troubleshooting channel.
