### ISSUE TITLE
Plugin source not available (violating license)

### ISSUE THREAD

**Issue by NotNite** [jawslouis/MakePlacePlugin#25]
Heya,

Your plugin's source code seems [intentionally out of sync with the releases](https://github.com/jawslouis/MakePlacePlugin/pull/24), which is a violation of the AGPL. Your plugin is required to follow this as a result of [Dalamud's license](https://github.com/goatcorp/Dalamud/blob/master/LICENSE). From Section 6:

> 6. Conveying Non-Source Forms.
>
> You may convey a covered work in object code form under the terms
> of sections 4 and 5, provided that you also convey the
> machine-readable Corresponding Source under the terms of this License,
> in one of these ways:

I suggest you update the published source code at your earliest convenience.

**Comment by jawslouis** [comment]
Hey, there are no plans to make the updated code public. 
People have been modifying the code to copy housing designs without permission from the original designer. 
As such, it is in the housing community's best interest for updates to the code to no longer be published. The MakePlace community agrees with this approach too.

**Comment by wwahammy** [comment]
@jawslouis you should really, really talk to a lawyer. If you don't comply with the AGPL and provide the source release, you can't use the software. If you do, you're engaging in copyright infringement.


Courts do not look kindly upon willful copyright infringement.
