### ISSUE TITLE
when loading a json, says placing, but nothing ever happens

### ISSUE THREAD

**Issue by thembees** [jawslouis/MakePlacePlugin#28]
hi there, so i installed the plugin, grabbed a simple 8-piece json file and put all the items down in the house, when i load the file is says, "Applying layout with interval of 400ms"

and nothing happens. 

try pressing load again, and it says, "Already placing items, imported 0 items" 

I have tried reinstalling the plugin, toggling it off and on, leaving my house and coming back, but nothing works.

**Comment by jawslouis** [comment]
Hi, you've probably used a Custom Design json file, which won't work with the plugin. Those are only for use with the simulator app. You'll need to use a full house layout for the plugin.

**Comment by thembees** [comment]
thanks for the reply! I did not see that information anywhere and will give that a try.
