### ISSUE TITLE
Changes revert after exiting indoor furnishings mode

### ISSUE THREAD

**Issue by somnifery** [jawslouis/MakePlacePlugin#30]
Seeing an issue where the plugin will make all changes, but as soon as I exit edit mode, they will revert or change positions of furnishings to different levels/locations. All plugins related (BDTH, makeplace, etc.) are up to date.

**Comment by jawslouis** [comment]
This is probably the issue you're facing. Unfortunately, it's a game limitation and the plugin can't fix that.
https://github.com/jawslouis/MakePlacePlugin?tab=readme-ov-file#why-does-the-furniture-snap-back-to-the-floorwall-after-i-apply-a-layout-and-exit-the-furnishing-menu
