### ISSUE TITLE
Cannot save layout

### ISSUE THREAD

**Issue by SayuriLuvixe** [jawslouis/MakePlacePlugin#33]
Updated makeplace after dalamud was back. Tried to save the current layout of my house and cannot. Help?

**Comment by SayuriLuvixe** [comment]
![Screenshot 2024-11-21 105209](https://github.com/user-attachments/assets/45656c8d-44be-44bb-ba8d-9bc49e47fd99)
Took a screenshot just in case that helps

**Comment by Scrxtchy** [comment]
I get this error when trying to save as well
```
10:55:15.276 | ERR | [MakePlacePlugin] Save Error: Object reference not set to an instance of an object.
10:55:15.276 | ERR | [MakePlacePlugin]    at MakePlacePlugin.SaveLayoutManager.LoadInteriorFixtures() in C:\Users\joshu\source\repos\MakePlacePlugin\MakePlacePlugin\SaveLayoutManager.cs:line 455
	   at MakePlacePlugin.MakePlacePlugin.LoadInterior() in C:\Users\joshu\source\repos\MakePlacePlugin\MakePlacePlugin\MakePlacePlugin.cs:line 620
	   at MakePlacePlugin.MakePlacePlugin.GetGameLayout() in C:\Users\joshu\source\repos\MakePlacePlugin\MakePlacePlugin\MakePlacePlugin.cs:line 702
	   at MakePlacePlugin.Gui.ConfigurationWindow.SaveLayoutToFile() in C:\Users\joshu\source\repos\MakePlacePlugin\MakePlacePlugin\Gui\ConfigurationWindow.cs:line 170
```

**Comment by SayuriLuvixe** [comment]
It's not just me! I don't feel alone  haha

**Comment by MrZifear** [comment]
Same issue.
![image](https://github.com/user-attachments/assets/7682fbb3-ed5d-4ffa-8b34-c5685f07a7fb)

**Comment by Scrxtchy** [comment]
![24-11-21_11-07-54-MakePlacePlugin_(Debugging)_-_Microsoft_Visual_Stu](https://github.com/user-attachments/assets/1b80c9c5-6d10-4dfd-bfb8-7972ba7d967f)

Yeah that'd do it

**Comment by Scrxtchy** [comment]
fixed in 1ab6cadabb0292ce69ab609ed5ec32848cf9fc38 (we came up with the same solution)
![image](https://github.com/user-attachments/assets/d08850e8-188e-4bd5-8590-6946486a43cb)

Thanks for getting this quick 🙏🏻

**Comment by SayuriLuvixe** [comment]
I can now save!!! But now this is happening, even after I left the housing menu   O.O
![Screenshot 2024-11-21 115452](https://github.com/user-attachments/assets/baa61aa2-f018-4621-bc64-317c326ac7e7)

**Comment by SayuriLuvixe** [comment]
Okay, was just something I did I think, as I left and re-entered and that didn't happen again. Thanks for updating the fix so quick   <3
