### ISSUE TITLE
Getting an error when trying to load a room from the app

### ISSUE THREAD

**Issue by tsuseo** [jawslouis/MakePlacePlugin#4]
![image](https://user-images.githubusercontent.com/80996573/178131420-40473fbc-a1c9-4589-860b-f9af53bafb50.png)

I'm getting the above error when loading a room from the MakePlace app. Both the application and the plugin are up to date.

**Comment by jawslouis** [comment]
Hi, there was a compatibility issue with the latest app update. The plugin has now been updated to work with the latest app version.
