### ISSUE TITLE
Wooden Showcases in room are greyed out of interior furniture

### ISSUE THREAD

**Issue by tsuseo** [jawslouis/MakePlacePlugin#5]
I have 6 Wooden Showcases in my room. When I load my file, I see the 6 wooden showcases in the list of interior furniture. However, they are greyed out. I also see them listed under the Unused Furniture section, even though they are also listed in the Interior Furniture section. There may be an ID mismatch.

![image](https://user-images.githubusercontent.com/80996573/178160885-f38cac13-848f-4ccb-8906-50ec0f804d08.png)

**Comment by jawslouis** [comment]
Do you have all floors checked in the plugin? It seems like your wooden showcases are slightly sunk into the floor, so it may be registering on the floor below. It will be grayed out if the corresponding floor is not selected in the plugin.

**Comment by tsuseo** [comment]
Interesting. I checked the basement and they appeared. I also tried putting them on a loft above the floor and they were still greyed out.

This is an image of the wooden showcases still being greyed out even though they're above ground level.
![image](https://user-images.githubusercontent.com/80996573/178171483-21da44a6-0d2d-47e8-9066-e2b3e52f7644.png)

And here's the same thing, but with the basement checked.
![image](https://user-images.githubusercontent.com/80996573/178171614-6c6b4cd1-2996-45ad-bed1-da3bf2afbf4f.png)

**Comment by jawslouis** [comment]
The furniture in the plugin will only be re-registered when you load a new layout, or select/unselect a floor.
So moving the wooden showcase above ground level will not make it register. And when you selected the basement floor, the wooden showcase got registered because it was on the ground floor and the ground floor was checked.
