### ISSUE TITLE
Can't load save files in plug in (Both plugin and make place updated)

### ISSUE THREAD

**Issue by aeowynsyrr** [jawslouis/MakePlacePlugin#6]
Keep on getting this error. Anyone knows how to fix it? 

Load Error: The JSON value could not be converted to System.Collections.Generic.Dictionary`2[System.String,System.Object]. Path: $.exteriorFurniture[0].properties | LineNumber: 1132 | BytePositionInLine: 18.

Thanks!

**Comment by jawslouis** [comment]
You'll need to resave the layout in the updated app, both for inside and outside. Based on the error, it looks like the outside was not re-saved in the app.

**Comment by aeowynsyrr** [comment]
Ah i see alright thanks!
