### ISSUE TITLE
Hello, when will you update v2.16

### ISSUE THREAD

**Issue by lansi1** [jawslouis/MakePlacePlugin#7]
Hello, when will you update v2.16

**Comment by jawslouis** [comment]
Why do you need an update from v2.16 - is there a feature you're looking for?

**Comment by lansi1** [comment]
> 为什么您需要 v2.16 的更新 - 是否有您正在寻找的功能？

Because I met such a problem：Load Error: The JSON value could not be converted to System.Collections.Generic.List`1[MakePlacePlugin.SaveProperty]. Path: $.interiorFurniture[0].properties | LineNumber: 119 | BytePositionInLine: 4.

**Comment by lansi1** [comment]
Sorry, I use the CN platform, but there is still an error

**Comment by jawslouis** [comment]
For issues with the CN version of the plugin, you'll have to get in touch with BlueFissure. The plugin on this github is for international servers only.

**Comment by lansi1** [comment]
How can I contact blue furniture




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jawslouis/MakePlacePlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 上午10:17
***@***.***&gt;;
抄送:&nbsp;"           ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jawslouis/MakePlacePlugin] Hello, when will you update v2.16 (Issue #7)





 
For issues with the CN version of the plugin, you'll have to get in touch with BlueFissure. The plugin on this github is for international servers only.

**Comment by lansi1** [comment]
Because I used makeplacev2.16 for decoration, I couldn't import the game when importing it. When checking the problem, I found that it was a version problem.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jawslouis/MakePlacePlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 凌晨1:04
***@***.***&gt;;
抄送:&nbsp;"           ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jawslouis/MakePlacePlugin] Hello, when will you update v2.16 (Issue #7)





 
Why do you need an update from v2.16 - is there a feature you're looking for?
