### ISSUE TITLE
Load error in plugin (2.16)

### ISSUE THREAD

**Issue by rendv** [jawslouis/MakePlacePlugin#8]
Trying to load my save from the latest version of the app (85) results in the following error:

Load Error: The JSON value could not be converted to System.Collections.Generic.Dictionary`2[System.String,System.String]. Path: $.properties.sunDirection | LineNumber: 918 | BytePositionInLine: 19.

**Comment by jawslouis** [comment]
Have you followed all the steps listed here?
https://github.com/jawslouis/MakePlacePlugin#im-getting-a-load-error

**Comment by lilyvelour** [comment]
@jawslouis would you be interested in a PR that handles upgrading files in the plugin itself? I made a working implementation of this as a standalone app, but I'd love to clean it up! I figure it would reduce issues like this as well.

Use case: I primarily use the plugin as a backup for housing layouts and do design work in-game. As a result, the app is very infrequently used.

**Comment by jawslouis** [comment]
Sure, that would be very welcome!
