### ISSUE TITLE
Let us export the list or layout

### ISSUE THREAD

**Issue by Kumicoo** [jawslouis/MakePlacePlugin#9]
Let us export lists and layout without housing menu, it is possible. I have another account but cant log in anymore since its stolen i want to save my house still asap. We can already get a list with every position, why not let us export it too? Please.

**Comment by Kumicoo** [comment]
Without being in furniture mode i mean

**Comment by jawslouis** [comment]
Letting a user save a house layout without having decorating permissions will allow anyone to copy house designs from others. Which is not in line with the intent of this plugin. So this will not be implemented.

**Comment by Kumicoo** [comment]
No problem i found another plugin, if anyone wants message me.
